pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        IMAGE_NAME = "sakethjooluri/food-ordering-frontend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('food-ordering-frontend') {
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                    sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest'
                }
            }
        }
        
        stage('Security Scan - Trivy') {
            steps {
                sh '''
                    trivy image --severity HIGH,CRITICAL \
                    --format json --output trivy-frontend-report.json \
                    ${IMAGE_NAME}:${IMAGE_TAG}
                '''
                archiveArtifacts artifacts: 'trivy-frontend-report.json'
            }
        }
        
        stage('Push to DockerHub') {
            steps {
                sh '''
                    echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${IMAGE_NAME}:latest
                '''
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    kubectl set image deployment/frontend \
                    frontend=${IMAGE_NAME}:${IMAGE_TAG} \
                    -n default
                    kubectl rollout status deployment/frontend -n default
                '''
            }
        }
    }
    
    post {
        always {
            sh 'docker logout'
        }
    }
}
